# Generated by Django 4.2.5 on 2023-10-06 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "primary_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "secondary_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("state", models.CharField(blank=True, max_length=70, null=True)),
                ("city", models.CharField(max_length=120)),
                ("zip_code", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("customer", "CUSTOMER"), ("seller", "SELLER")]
                    ),
                ),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=70)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "address",
                    models.ManyToManyField(
                        related_name="userprofile", to="users.useraddress"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
