# Generated by Django 4.2.5 on 2023-10-08 10:04

from django.db import migrations, models
import src.apps.orders.utils


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_place_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_deadline",
            field=models.DateField(default=src.apps.orders.utils.payment_deadline_calc),
        ),
    ]
