# Generated by Django 4.2.5 on 2023-10-08 10:07

from django.db import migrations, models
import src.apps.orders.utils


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_order_place_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_place_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_deadline",
            field=models.DateTimeField(
                default=src.apps.orders.utils.payment_deadline_calc
            ),
        ),
    ]
