# Generated by Django 4.2.5 on 2023-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
