# Generated by Django 4.2.5 on 2023-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productinventory",
            name="sold",
        ),
    ]
