# Generated by Django 4.2.5 on 2023-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_productinventory_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
